# Generated by Django 4.2.30 on 2026-07-15 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_deal_emailsequence_emailsequencestep_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('log_output', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('project_type', models.CharField(choices=[('web', 'Web Application'), ('mobile', 'Mobile App'), ('api', 'API Integration'), ('migration', 'Cloud Migration'), ('data', 'Data Analytics/Engineering'), ('ai', 'AI/ML Model Development'), ('other', 'Other Custom Software')], default='other', max_length=50)),
                ('project_title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('tech_preferences', models.TextField(blank=True, null=True)),
                ('budget_range', models.CharField(choices=[('10k', 'Under $10,000'), ('25k', '$10,000 - $25,000'), ('50k', '$25,000 - $50,000'), ('100k', '$50,000 - $100,000'), ('100k+', '$100,000+'), ('discuss', "Not Sure / Let's Discuss")], default='discuss', max_length=20)),
                ('timeline', models.CharField(choices=[('asap', 'ASAP (Urgent)'), ('1mo', 'Within 1 Month'), ('3mo', '1-3 Months'), ('6mo', '3-6 Months'), ('flexible', 'Flexible / No Rush')], default='flexible', max_length=20)),
                ('has_existing_codebase', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New Request'), ('review', 'Under Review'), ('scoping', 'Scoping / Estimating'), ('approved', 'Approved / Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop / Computer'), ('mobile', 'Mobile Device'), ('server', 'Server / Infrastructure'), ('network', 'Network Equipment'), ('software', 'Software License'), ('other', 'Other')], default='laptop', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active / In Use'), ('available', 'Available in Inventory'), ('in_repair', 'In Repair'), ('retired', 'Retired / Decommissioned'), ('lost', 'Lost / Stolen')], default='available', max_length=50)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ITTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('p1', 'P1 - Critical'), ('p2', 'P2 - High'), ('p3', 'P3 - Medium'), ('p4', 'P4 - Low')], default='p3', max_length=10)),
                ('category', models.CharField(choices=[('network', 'Network / Connectivity'), ('hardware', 'Hardware'), ('software', 'Software / Applications'), ('cloud', 'Cloud Infrastructure'), ('security', 'Security Incident'), ('access', 'Access / Permissions'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('pending_user', 'Pending User Info'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('device_asset_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('csat_triggered', models.BooleanField(default=False)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_status', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('breached', 'Breached')], default='healthy', max_length=20)),
                ('first_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolve_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tracking_app.itasset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ITVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('support_portal_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SLAConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('p1', 'P1 - Critical'), ('p2', 'P2 - High'), ('p3', 'P3 - Medium'), ('p4', 'P4 - Low')], max_length=10, unique=True)),
                ('first_response_hours', models.FloatField(help_text='Hours until first response is required')),
                ('resolution_hours', models.FloatField(help_text='Hours until full resolution is required')),
                ('escalation_priority', models.CharField(blank=True, choices=[('p1', 'P1 - Critical'), ('p2', 'P2 - High'), ('p3', 'P3 - Medium'), ('p4', 'P4 - Low')], help_text='Priority to bump to if breached', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_minutes', models.PositiveIntegerField(help_text='Time spent in minutes')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='tracking_app.itticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='tracking_app.itticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('response_text', models.TextField()),
                ('auto_status', models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('pending_user', 'Pending User Info'), ('resolved', 'Resolved'), ('closed', 'Closed')], max_length=20, null=True)),
                ('auto_priority', models.CharField(blank=True, choices=[('p1', 'P1 - Critical'), ('p2', 'P2 - High'), ('p3', 'P3 - Medium'), ('p4', 'P4 - Low')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tracking_app.itticket')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('malware', 'Malware / Ransomware'), ('phishing', 'Phishing / Social Engineering'), ('ddos', 'DDoS Attack'), ('data_breach', 'Data Breach / Leak'), ('unauthorized_access', 'Unauthorized Access'), ('insider_threat', 'Insider Threat'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=20)),
                ('detection_source', models.CharField(blank=True, max_length=150, null=True)),
                ('file_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('affected_system', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('it_metrics', 'IT Helpdesk Metrics'), ('sec_summary', 'Security Incident Summary'), ('sla_breach', 'SLA Breach Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('recipients', models.TextField(help_text='Comma separated email addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('network', 'Network / Connectivity'), ('hardware', 'Hardware'), ('software', 'Software / Applications'), ('cloud', 'Cloud Infrastructure'), ('security', 'Security Incident'), ('access', 'Access / Permissions'), ('other', 'Other')], max_length=50, unique=True)),
                ('assign_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'it_agent']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ITTicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracking_app.itticket')),
            ],
        ),
        migrations.AddField(
            model_name='itasset',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='tracking_app.itvendor'),
        ),
    ]
