# Generated by Django 5.2 on 2026-01-20 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_user_headline_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the saved search', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills_filter', models.JSONField(default=list, help_text='Required skills')),
                ('experience_min', models.FloatField(blank=True, null=True)),
                ('experience_max', models.FloatField(blank=True, null=True)),
                ('location_filter', models.JSONField(default=list, help_text='Location preferences')),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('job_type_filter', models.JSONField(default=list, help_text='Job types')),
                ('education_filter', models.JSONField(default=list, help_text='Education requirements')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('last_used_date', models.DateTimeField(blank=True, null=True)),
                ('result_count', models.IntegerField(default=0, help_text='Number of results from last search')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateAISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_summary', models.TextField(help_text='AI-generated professional summary')),
                ('key_strengths', models.JSONField(default=list, help_text='Top 5 key strengths')),
                ('development_areas', models.JSONField(default=list, help_text='Areas for development')),
                ('ideal_roles', models.JSONField(default=list, help_text='Recommended job roles')),
                ('overall_profile_score', models.IntegerField(help_text='Overall candidate quality score 0-100')),
                ('communication_score', models.IntegerField(help_text='Communication skills score')),
                ('technical_score', models.IntegerField(help_text='Technical skills score')),
                ('leadership_score', models.IntegerField(help_text='Leadership potential score')),
                ('summary_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('generated_by', models.CharField(default='ai_engine', max_length=50)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='tracking_app.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('skills', models.JSONField(default=list, help_text='List of extracted skills with proficiency levels')),
                ('experience_years', models.FloatField(blank=True, help_text='Total years of experience', null=True)),
                ('education', models.JSONField(default=list, help_text='List of education details')),
                ('certifications', models.JSONField(default=list, help_text='List of certifications')),
                ('raw_text', models.TextField(blank=True, help_text='Raw extracted text from resume', null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('parsed_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume_data', to='tracking_app.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPartyIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('bullhorn', 'Bullhorn'), ('linkedin', 'LinkedIn'), ('greenhouse', 'Greenhouse'), ('workday', 'Workday'), ('generic_api', 'Generic API')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('api_endpoint', models.URLField(blank=True, help_text='Custom API endpoint for generic APIs', null=True)),
                ('field_mappings', models.JSONField(default=dict, help_text='Mapping of internal fields to provider fields')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('last_sync_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(help_text="e.g., 'sync_candidates', 'sync_jobs'", max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partially Synced')], default='pending', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_successful', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tracking_app.thirdpartyintegration')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(help_text='Overall match score 0-100')),
                ('skill_match_score', models.IntegerField(help_text='Skill match percentage')),
                ('experience_match_score', models.IntegerField(help_text='Experience match percentage')),
                ('education_match_score', models.IntegerField(help_text='Education match percentage')),
                ('culture_fit_score', models.IntegerField(help_text='Culture fit percentage')),
                ('availability_score', models.IntegerField(help_text='Availability match percentage')),
                ('matching_skills', models.JSONField(default=list, help_text='Skills that match job requirements')),
                ('missing_skills', models.JSONField(default=list, help_text="Required skills candidate doesn't have")),
                ('experience_gap', models.TextField(blank=True, help_text='Experience gaps analysis', null=True)),
                ('recommendations', models.JSONField(default=list, help_text='Recommendations for improvement')),
                ('is_auto_matched', models.BooleanField(default=False, help_text='Auto-matched by AI algorithm')),
                ('calculated_date', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='tracking_app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_matches', to='tracking_app.job')),
            ],
            options={
                'ordering': ['-overall_score'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='FieldMappingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_field', models.CharField(help_text='Field name in our system', max_length=100)),
                ('external_field', models.CharField(help_text='Field name in external system', max_length=100)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('date', 'Date'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('is_bidirectional', models.BooleanField(default=False, help_text='Sync in both directions')),
                ('transform_function', models.CharField(blank=True, help_text='Optional data transformation', max_length=255, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to='tracking_app.thirdpartyintegration')),
            ],
            options={
                'unique_together': {('integration', 'internal_field', 'external_field')},
            },
        ),
    ]
