# Generated by Django 4.2.30 on 2026-07-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0003_automationrun_devprojectrequest_itasset_itticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatincident',
            name='attack_vector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatincident',
            name='estimated_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatincident',
            name='ioc_indicators',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threatincident',
            name='malicious_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='threatincident',
            name='response_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
