# Generated by Django 4.2.30 on 2026-07-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0004_threatincident_attack_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='it_tickets/'),
        ),
        migrations.AddField(
            model_name='itticket',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
