# Generated by Django 4.2.30 on 2026-07-15 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0005_itticket_attachment_itticket_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHoursSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('work_start_time', models.TimeField(default='09:00:00')),
                ('work_end_time', models.TimeField(default='17:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('access', 'Access Request')], max_length=50)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requires_approval', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('condition_category', models.CharField(blank=True, choices=[('network', 'Network / Connectivity'), ('hardware', 'Hardware'), ('software', 'Software / Applications'), ('cloud', 'Cloud Infrastructure'), ('security', 'Security Incident'), ('access', 'Access / Permissions'), ('other', 'Other')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_assign_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField()),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending_approval', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking_app.servicecatalogitem')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ITProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('workaround', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Root Cause Identified'), ('resolved', 'Resolved')], default='investigating', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_tickets', models.ManyToManyField(blank=True, related_name='problems', to='tracking_app.itticket')),
            ],
        ),
        migrations.CreateModel(
            name='ITChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('backout_plan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('pending_cab', 'Pending CAB Approval'), ('approved', 'Approved'), ('implemented', 'Implemented'), ('rejected', 'Rejected')], default='planning', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeApprovalBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cab_votes', to='tracking_app.itchangerequest')),
            ],
        ),
        migrations.CreateModel(
            name='AssetRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('runs_on', 'Runs On'), ('depends_on', 'Depends On')], max_length=50)),
                ('dependent_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_rels', to='tracking_app.itasset')),
                ('primary_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_rels', to='tracking_app.itasset')),
            ],
        ),
    ]
