# Generated by Django 4.2.30 on 2026-07-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0009_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_ats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_executive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_it',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_sales',
            field=models.BooleanField(default=True),
        ),
    ]
