# Generated by Django 4.2.30 on 2026-07-20 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0010_user_can_view_ats_user_can_view_executive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountactivity',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_activities_log', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='accountcontact',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_contacts', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='application',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='interview',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='itticket',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='itvendor',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='threatincident',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='tracking_app.tenant'),
        ),
    ]
