# Generated by Django 4.2.30 on 2026-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0011_accountactivity_tenant_accountcontact_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter — $49/mo'), ('growth', 'Growth — $149/mo'), ('enterprise', 'Enterprise — $399/mo')], default='enterprise', max_length=32),
        ),
    ]
