# Generated by Django 4.2.30 on 2026-07-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0012_tenant_stripe_customer_id_tenant_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('recruiter', 'Recruiter / HR'), ('sales', 'Sales Professional'), ('it', 'IT Helpdesk Agent'), ('admin', 'Administrator')], default='jobseeker', help_text='Designates the role and permissions of this user.', max_length=20),
        ),
    ]
