# Generated by Django 4.2.30 on 2026-07-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0014_webhookendpoint_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailreply',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_replies', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Registered tenant sender email address used', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='outreachemail',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outreach_emails', to='tracking_app.tenant'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_auto_sync',
            field=models.BooleanField(default=True, help_text='Automatically parse and sync two-way email communications'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_integration_status',
            field=models.CharField(choices=[('unconfigured', 'Unconfigured'), ('connected', 'Connected & Active'), ('error', 'Connection Warning')], default='unconfigured', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_registered_email',
            field=models.EmailField(blank=True, help_text='Registered corporate email address for sending and receiving', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_reply_to',
            field=models.EmailField(blank=True, help_text='Dedicated inbound inbox for automated AI reply parsing', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_sender_name',
            field=models.CharField(blank=True, help_text='Sender display name (e.g., Nexus AI Sales)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_smtp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_smtp_port',
            field=models.IntegerField(blank=True, default=587, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_smtp_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
