# Generated by Django 4.2.30 on 2026-07-29 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0015_emailreply_tenant_outreachemail_sender_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_score', models.IntegerField(default=3)),
                ('communication_score', models.IntegerField(default=3)),
                ('culture_fit_score', models.IntegerField(default=3)),
                ('problem_solving_score', models.IntegerField(default=3)),
                ('overall_rating', models.IntegerField(default=3)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('weaknesses', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(choices=[('hire', 'Strong Hire'), ('maybe', 'Maybe'), ('reject', 'No Hire')], default='maybe', max_length=20)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='tracking_app.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
