# Generated by Django 4.2.30 on 2026-08-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0016_interviewscorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gmaps_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gmaps_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gmaps_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gmaps_place_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gmaps_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gmaps_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('apollo', 'Apollo.io'), ('linkedin', 'LinkedIn'), ('serp', 'Job Board Scrape'), ('manual', 'Manual Entry'), ('inbound', 'Inbound (Website)'), ('referral', 'Referral'), ('google_maps', 'Google Maps Scraper')], default='manual', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='unique_lead_email_when_not_null'),
        ),
    ]
