# Generated by Django 4.2.30 on 2026-08-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0018_leadfolder_lead_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOutreachRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial (some channels failed)'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('icp_score', models.FloatField(default=0.0)),
                ('skip_reason', models.CharField(blank=True, max_length=300, null=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_subject', models.CharField(blank=True, max_length=400)),
                ('email_body', models.TextField(blank=True)),
                ('email_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_opened', models.BooleanField(default=False)),
                ('email_clicked', models.BooleanField(default=False)),
                ('email_replied', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('sms_body', models.TextField(blank=True)),
                ('sms_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('call_enabled', models.BooleanField(default=False)),
                ('call_script', models.TextField(blank=True)),
                ('call_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('call_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('call_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('call_duration_seconds', models.IntegerField(default=0)),
                ('sequence_enrolled', models.BooleanField(default=False)),
                ('sequence_step', models.IntegerField(default=0)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('goal', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('complete', 'Complete'), ('archived', 'Archived')], default='active', max_length=20)),
                ('channel_email', models.BooleanField(default=True)),
                ('channel_sms', models.BooleanField(default=True)),
                ('channel_call', models.BooleanField(default=False)),
                ('personalization_level', models.CharField(choices=[('quick', 'Quick (Fast, template-based)'), ('standard', 'Standard (AI-personalized per lead)'), ('deep', 'Deep (Research + multi-signal context)')], default='standard', max_length=20)),
                ('enroll_in_sequence', models.BooleanField(default=True)),
                ('sequence_days', models.JSONField(default=list)),
                ('leads_targeted', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('sms_sent', models.IntegerField(default=0)),
                ('calls_initiated', models.IntegerField(default=0)),
                ('replies_received', models.IntegerField(default=0)),
                ('demos_booked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outreach_campaigns', to='tracking_app.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachAgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('ai', 'AI Decision')], default='info', max_length=10)),
                ('channel', models.CharField(blank=True, choices=[('email', 'Email'), ('sms', 'SMS'), ('call', 'Call'), ('system', 'System'), ('ai', 'AI')], max_length=20)),
                ('message', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_logs', to='tracking_app.lead')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tracking_app.agentoutreachrun')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='tracking_app.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentoutreachrun',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tracking_app.outreachcampaign'),
        ),
        migrations.AddField(
            model_name='agentoutreachrun',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='tracking_app.lead'),
        ),
        migrations.AddField(
            model_name='agentoutreachrun',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='tracking_app.tenant'),
        ),
    ]
