# Generated by Django 4.2.30 on 2026-08-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0020_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcontact',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='devprojectrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='devprojectrequest',
            name='contact_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itvendor',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mail_sender_name',
            field=models.CharField(blank=True, help_text='Sender display name (e.g., Nexus AI Sales)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mail_smtp_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='mail_smtp_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='threatincident',
            name='detection_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketroutingrule',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
