# Generated by Django 4.2.30 on 2026-08-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0021_alter_accountcontact_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to company logo', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='portal_domain',
            field=models.CharField(blank=True, help_text='Custom domain', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#00E5FF', help_text='Hex color code', max_length=7),
        ),
    ]
