# Generated by Django 4.2.30 on 2026-08-31 20:38

from django.db import migrations, models
import tracking_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0022_tenant_logo_url_tenant_portal_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tracking_app.models.tenant_media_path),
        ),
        migrations.AlterField(
            model_name='jobseekerapplication',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=tracking_app.models.tenant_media_path),
        ),
        migrations.AlterField(
            model_name='resumedata',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=tracking_app.models.tenant_media_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=tracking_app.models.tenant_media_path),
        ),
    ]
