# Generated by Django 4.2.30 on 2026-08-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0024_automationrule_automationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='mail_app_password',
            field=models.CharField(blank=True, help_text='Encrypted or secure App Password for IMAP/SMTP sync', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_imap_host',
            field=models.CharField(blank=True, default='imap.gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mail_imap_port',
            field=models.IntegerField(blank=True, default=993, null=True),
        ),
    ]
