# Generated by Django 4.2.30 on 2026-08-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0025_tenant_mail_app_password_tenant_mail_imap_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='custom_field_schema',
            field=models.JSONField(blank=True, default=dict, help_text="Defines custom fields per module, e.g. {'lead': [{'name': 'Industry', 'type': 'text'}]}", null=True),
        ),
    ]
