# Generated by Django 4.2.30 on 2026-08-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0026_tenant_custom_field_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='itticket',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
