# Generated by Django 4.2.30 on 2026-08-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0027_deal_custom_data_itticket_custom_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='churn_analysis_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='churn_risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='churn_risk_score',
            field=models.IntegerField(default=0, help_text='0-100 score indicating churn probability based on cross-module AI analysis.'),
        ),
    ]
