# Generated by Django 4.2.30 on 2026-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0028_deal_churn_analysis_summary_deal_churn_risk_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('recruiter', 'Recruiter / HR'), ('sales', 'Sales Professional'), ('it', 'IT Helpdesk Agent'), ('admin', 'Administrator'), ('client', 'External Client')], default='jobseeker', help_text='Designates the role and permissions of this user.', max_length=20),
        ),
    ]
