# Generated by Django 4.2.30 on 2026-09-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_setup_google_oauth_site'),
        ('tracking_app', '0029_alter_user_role'),
    ]

    operations = [
    ]
