# Generated by Django 4.2.30 on 2026-09-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0030_merge_20260911_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text="Tenant's Gemini API Key", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text="Tenant's OpenAI API Key", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='twilio_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
