# Generated by Django 4.2.30 on 2026-09-30 22:57

from django.db import migrations


def upgrade_user(apps, schema_editor):
    User = apps.get_model('tracking_app', 'User')
    Tenant = apps.get_model('tracking_app', 'Tenant')
    from django.contrib.auth.hashers import make_password
    
    tenant = Tenant.objects.first()
    
    user, created = User.objects.get_or_create(
        email='j@transform-tech.com',
        defaults={
            'username': 'jmartin',
            'password': make_password('Admin123!'),
            'first_name': 'J',
            'last_name': 'Martin',
            'is_superuser': True,
            'is_staff': True,
            'tenant': tenant,
            'role': 'admin',
            'can_view_executive': True,
            'can_view_sales': True,
            'can_view_ats': True,
            'can_view_it': True,
        }
    )
    if not created:
        user.is_superuser = True
        user.is_staff = True
        if not user.tenant:
            user.tenant = tenant
        user.role = 'admin'
        user.can_view_executive = True
        user.can_view_sales = True
        user.can_view_ats = True
        user.can_view_it = True
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0031_tenant_gemini_api_key_tenant_openai_api_key_and_more'),
    ]

    operations = [
        migrations.RunPython(upgrade_user),
    ]
