"""
Django settings for ats_crm_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m6b6gv*^g_1nimg*3a5ow*8x=szk*gg=gs*z-&!#@as=uk_x#m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracking_app',
    'video',
    'channels',
    # Phase 2 — Celery + Billing
    'django_celery_beat',
    'django_celery_results',
    'djstripe',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Phase 2 — SaaS Feature Gating
    'tracking_app.middleware.FeatureGatingMiddleware',
]

ROOT_URLCONF = 'ats_crm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tracking_app.views.add_global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'ats_crm_project.wsgi.application'
ASGI_APPLICATION = 'ats_crm_project.asgi.application'

# ── Database ─────────────────────────────────────────────────
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# ── Password Validation ───────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ── Internationalisation ──────────────────────────────────────
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ── Static / Media ────────────────────────────────────────────
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'tracking_app.User'
LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = [
    'https://26464c660ea8.ngrok-free.app',
    'https://preview-jaisu-8000.loca.lt',
    'https://campsite-december-flatly.ngrok-free.dev',
]

# ── WebSocket Channel Layers ──────────────────────────────────
# Uses Redis when REDIS_URL is set, otherwise InMemory (dev fallback)
_REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')
_USE_REDIS = False
try:
    import redis as _redis_module
    _r = _redis_module.from_url(_REDIS_URL, socket_connect_timeout=1)
    _r.ping()
    _USE_REDIS = True
except Exception:
    pass  # Redis not available — use InMemory

if _USE_REDIS:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [_REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {'BACKEND': 'channels.layers.InMemoryChannelLayer'}
    }

# ── Email (Console for Local Testing) ────────────────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'jaisukhwal41@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'zgihpkfvtwliixrg')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# ── AI / OpenAI ───────────────────────────────────────────────
# Set OPENAI_API_KEY in your environment (never hardcode keys)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# ── Celery Configuration ──────────────────────────────────────
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', _REDIS_URL)
CELERY_RESULT_BACKEND = 'django-db'           # via django-celery-results
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# ── Celery Beat Schedule (periodic tasks) ────────────────────
from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'scan-sla-breaches': {
        'task': 'tracking_app.tasks.scan_sla_breaches',
        'schedule': 900.0,  # every 15 minutes
    },
    'run-sales-alerts': {
        'task': 'tracking_app.tasks.run_sales_alerts',
        'schedule': 3600.0,  # every hour
    },
    'sync-imap-inbox': {
        'task': 'tracking_app.tasks.sync_imap_inbox',
        'schedule': 600.0,  # every 10 minutes
    },
    'send-weekly-digest': {
        'task': 'tracking_app.tasks.send_weekly_digest',
        'schedule': crontab(hour=8, minute=0, day_of_week='monday'),
    },
    'cleanup-old-data': {
        'task': 'tracking_app.tasks.cleanup_old_data',
        'schedule': crontab(hour=0, minute=30),  # daily at 00:30 UTC
    },
}

# ── Stripe Configuration ──────────────────────────────────────
STRIPE_LIVE_MODE = False  # Set True in production
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Stripe Price IDs — create these in your Stripe dashboard
STRIPE_PRICE_STARTER = os.getenv('STRIPE_PRICE_STARTER', '')
STRIPE_PRICE_GROWTH = os.getenv('STRIPE_PRICE_GROWTH', '')
STRIPE_PRICE_ENTERPRISE = os.getenv('STRIPE_PRICE_ENTERPRISE', '')

DJSTRIPE_WEBHOOK_SECRET = STRIPE_WEBHOOK_SECRET
DJSTRIPE_FOREIGN_KEY_TO_FIELD = 'id'

# ── Caching & Redis ───────────────────────────────────────────
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
    }
}

# ── Celery Configuration ──────────────────────────────────────
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ── Production Security Settings ──────────────────────────────
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True




